# Generated by Django 4.2.26 on 2025-11-16 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import secrets


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.TextField()),
                ('encrypted_private_key', models.TextField()),
                ('private_key_nonce', models.CharField(max_length=128)),
                ('private_key_salt', models.CharField(max_length=128)),
                ('private_key_iterations', models.PositiveIntegerField(default=390000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_rotated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_message', models.TextField(blank=True)),
                ('encrypted_attachment', models.TextField(blank=True)),
                ('attachment_name', models.CharField(blank=True, max_length=255)),
                ('attachment_mime', models.CharField(blank=True, max_length=255)),
                ('encrypted_symmetric_key', models.TextField()),
                ('message_nonce', models.CharField(blank=True, max_length=64)),
                ('attachment_nonce', models.CharField(blank=True, max_length=64)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=secrets.token_hex, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
